-- AlterTable
ALTER TABLE "Skin" ADD COLUMN     "priceMax" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceMin" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
